name: Build (test)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild simc_vs2026.sln /p:Configuration=Release /p:Platform=x64

      - name: Package build
        shell: pwsh
        run: |
          mkdir release-package
          copy bin\x64\Release\simc.exe release-package\
          Copy-Item -Recurse apl release-package\apl
          Copy-Item -Recurse profiles release-package\profiles
          Compress-Archive -Path release-package\* -DestinationPath simc-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simc-windows-build
          path: simc-windows.zip
