name: Build Windows exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Force C++20 override
        shell: pwsh
        run: |
          @"
          <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <ItemDefinitionGroup>
              <ClCompile>
                <AdditionalOptions>%(AdditionalOptions) /std:c++20</AdditionalOptions>
              </ClCompile>
            </ItemDefinitionGroup>
          </Project>
          "@ | Out-File -FilePath cxx20_override.props -Encoding utf8

      - name: Build
        run: msbuild simc_vs2022.sln /p:Configuration=Release /p:Platform=x64 /p:ForceImportAfterCppTargets=cxx20_override.props

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: simc-windows-build
          path: |
            **/*.exe
